### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by abdulbadii** [bartoszek/AUR-phonon-qt4#1]
How to solve this, when building phonon-qt4:
```
...
...
==> Verifying source file signatures with gpg...
phonon-4.10.3.tar.xz ... FAILED (unknown public key B92A5F04EC949121)
==> ERROR: One or more PGP signatures could not be verified!
```
Please explain the solution in clear detailed step by step

**Comment by bartoszek** [comment]
Man, It's referenced in the [pinned comment](https://aur.archlinux.org/packages/phonon-qt4#pinned-668765) :grin: 
You basically have two options:
 * Add pgp key to your keyring: `gpg --recv-keys B92A5F04EC949121`
 * Build without pgp verification: `makepkg --skippgpcheck` 
Former is the preferred way, as it increases security.

**Comment by abdulbadii** [comment]
Works like a charm !!
